### ISSUE TITLE
npm install fails on git rev-list command

### ISSUE THREAD

**Issue by jmjpro** [PolymerElements/paper-styles#101]
I would like to try out this package after it has a working default npm install. Currently I get:

`git rev-list -n1 %5E1.0.1: fatal: ambiguous argument '%5E1.0.1': unknown revision or path not in the working tree.`

**Comment by notwaldorf** [comment]
Currently we only support `bower` to install elements, but we're working on a better `npm` answer.

**Comment by justinfagnani** [comment]
@jmjpro `npm i @polymer/paper-styles` works for me. How were trying to install this?

**Comment by justinfagnani** [comment]
FYI, the npm workflow is _just_ being worked on now, and it's very much bleeding-edge, unsupported territory. We haven't checked in our `package.json` files yet, verified that all of our packages work via npm, or publicized the packages.

Since the install worked for me, I'm going to close this for now. It's possible that you were trying to use un-official packages that were published by someone else, or are trying to use a git install. If not, feel free to reopen if the problem persists with `@polymer/paper-styles`. Thanks!
