### ISSUE TITLE
--paper-font-common-nowrap fails to show ellipsis

### ISSUE THREAD

**Issue by IntranetFactory** [PolymerElements/paper-styles#106]
--paper-font-common-nowrap shows the ellipsis only if  `display: block` is added

```
    --paper-font-common-nowrap: {
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
      display: block;
    };
```

**Comment by notwaldorf** [comment]
I'm a little worried about adding `block` like that, since it would override any `display: inline-block` the user might have, which also works: http://jsbin.com/felevu/edit?html,output

I think it makes sense that you should add `display: block` to the element you're adding the mixin to (but maybe it would be nice to document that).

Would you like to send a PR adding a comment above the mixin, that block or inline block are required?

**Comment by IntranetFactory** [comment]
I think if you add `display: inline-block;` is also ok. But without either of them it's just nowrap - as both overflow and text-overflow have no impact. So maybe these two lines should be removed if they don't work without additional settings in the element where the mixin is added and a new, working `--paper-font-common-overflow-ellipsis` should be added?

**Comment by notwaldorf** [comment]
But I think they work fine -- you just need to apply them to an element that makes sense. If you're applying them to something with `display:inline`, widths and heights are ignored, so you're never going to need the ellipsis.

Do you have a concrete example to what you're trying to apply it to and it doesn't work? If it's something like a `span`, it's because the span is `display:inline` and ignores any width you set on it, which also means there won't be any overflow

**Comment by IntranetFactory** [comment]
We applied it to an iron-label and had been "surprised" that we didn't get ellipsis. But if the current state is ok, then we'll just adjust it in our themes.
