### ISSUE TITLE
--text-primary-color and --primary-text-color have different values

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/paper-styles#110]
I just filed this:

https://github.com/PolymerElements/paper-fab/issues/69

I was trying to figure out what to recommend them for a replacement of `--text-primary-color`, when I realised that in the default theme `--text-primary-color` is assigned a _different_ value to `primary-text-color`.

So... why is that? And what should paper-fab use instead?

Plus (bonus question), wouldn't it be better to get rid of the whole dark/light values and turn the theme into:

         /*
         * Primary and accent colors for text. Also see color.html for more colors.
         */
        --primary-text-color: var(--paper-grey-900);
        --primary-background-color: #ffffff;
        --secondary-text-color: #737373;
        --disabled-text-color: #9b9b9b;
        --divider-color: #dbdbdb;;
        --error-color: var(--paper-deep-orange-a700);

        /*
         * Primary and accent colors. Also see color.html for more colors.
         */
        --primary-color: var(--paper-indigo-500);
        --light-primary-color: var(--paper-indigo-100);
        --dark-primary-color: var(--paper-indigo-700);

        --accent-color: var(--paper-pink-a200);
        --light-accent-color: var(--paper-pink-a100);
        --dark-accent-color: var(--paper-pink-a400);

...?

**Comment by notwaldorf** [comment]
Yeah, these 2 properties were originally very poorly named, which is why one of them is now deprecated: https://github.com/PolymerElements/paper-styles/blob/master/default-theme.html#L67. We can't remove it altogether, since that could constitute a breaking change.

Secondly, the dark/light values are there so that you can use the values in your application, without having to look the up in the spec. You don't _have_ to use them, but if you need to, they're there.

**Comment by mercmobily** [comment]
OK. My point was that *having* them was cause of confusion more than help. The fact that somebody ended up using it *within* Polymer makes my point even stronger....

**Comment by notwaldorf** [comment]
Soooo I'm not sure I understand about which "them" you're referring to:

- if it's the primary-text-color/text-primary-color: a year and a half ago, someone created these badly named properties. We shipped them, used them unevenly in all the elements, and realized they were badly named. You have to realize that more than one person works on the 100+ Polymer elements we own, and sometimes we make mistakes. We can't delete these badly named properties, since that's a breaking change. I deprecated one of them, and we are trying not to use it internally. I haven't had a chance to go and update all the repos that might still be using it. When we can ship a breaking change, we will delete the deprecated property, and everything will be fine. In the meantime, if you want to update the repos that still use the deprecated one, those PRs will be appreciated.

- if it's the light/dark properties, we are using them because giving a name to a hardcoded colour helps track what it actually means. Most polymer elements use the "light" material design theme, and that's why those theme properties default to the "light" theme values.

**Comment by mercmobily** [comment]
My bad, I was taking about the "theme" values. I am going to be more specific. But please correct me if I am wrong...

To me, these "theme" values (`--light-theme-*` and `--dark-theme-*`) should never ever be used directly by Polymer elements, and should only ever live in the `default-theme.html` file. The `--light-theme-*` and `--dark-theme-*` values  are "meta-values" that are then used, _within_ the `default-theme.html` file, to assign the _actual_ values ( `--primary-text-color`, `--primary-background-color`, `--secondary-text-color`, `--disabled-text-color`, `--divider-color`, `--error-color`)  which elements then use, redefine, etc.. Elements should never be based on, nor re-set, the  `--light-theme-*` and `--dark-theme-*` values.

It needs to be this way, with `--light-theme-*` and `--dark-theme-*` only used within `default-theme.html` to set the "real" Paper CSS custom properties. If that wasn't the case,  it would mean that Polymer elements would have to consider (and set, and use), at all times, _two_ sets of values: BOTH (`--primary-text-color`, `--primary-background-color`, etc.) AND  `--light-theme-*` and `--dark-theme-*`  _which then influence them the first set within `default-theme.html`.

So once it's established that `--light-theme-*` and `--dark-theme-*` are aids to set `default-theme.html` more quickly, then... here I am questioning if they are confusing.

Because then keanulee was saying [https://github.com/PolymerElements/paper-fab/issues/69#issuecomment-219105945]("Should replace it [`--text-primary-color` ] with `--dark-theme-text-color` to keep the default value consistent.") (!). 

And then you get a widget, paper-toolbar, that is doing [`--text-primary-color: var(--dark-theme-text-color);`]( 
https://github.com/PolymerElements/paper-toolbar/blob/master/paper-toolbar.html#L119)

So yes, are they ( `--light-theme-*` and `--dark-theme-*` values) not generating confusion?

**Comment by notwaldorf** [comment]
Hmm, I don't see why it would be bad to use them directly in elements...I don't think that was my intention, and I don't think I wrote that in the docs...The MD spec defined two kinds of themes (https://www.google.com/design/spec/style/color.html#color-text-background-colors), and I thought it would be useful for people if they were actually defined somewhere.

The intention behind `--primary-text-color` like properties was to be able to style all the paper elements at once. Most of our elements just implement the light theme, which is why the `--primary-text-color` properties and friends default to the `--light-theme-*` properties. If you wanted to change all the paper elements in your app to use the dark theme, the easiest way to do this would be to update the  `--primary-text-color` properties and friends to point to the `--dark-theme-*` equivalents. 

`paper-fab` in particular lives in a special world, where it's technically using the dark theme values -- so i think it would be fine for it to use `--dark-theme-text-color` directly, since that's what it actually needs. It can't use the default `--primary-text-color` because it's using the exact opposite theme of whatever the other elements use (also, if the other elements were switched to use the dark theme, paper-fab would need to independently switch to `--dark-theme-text-color`

Does this help at all?

**Comment by mercmobily** [comment]
--------------------
Hmm, I don't see why it would be bad to use them directly in elements...I don't think that was my intention, and I don't think I wrote that in the docs...The MD spec defined two kinds of themes (https://www.google.com/design/spec/style/color.html#color-text-background-colors), and I thought it would be useful for people if they were actually defined somewhere, with sane names, so that you could use --light-theme-disabled-color instead of #ededed.
-----------------------

OK.

--------------------------------------------------------
The intention behind the --primary-text-color like properties was to be able to style all the paper elements at once. Most of our elements just implement the light theme, which is why the --primary-text-color properties and friends default to the --light-theme-* properties. If you wanted to change all the paper elements in your app to use the dark theme, the easiest way to do this would be to update the --primary-text-color properties and friends to point to the --dark-theme-* equivalents.
----------------------------------------------------------
OK.

-----------------------------------------------------------------------
paper-fab in particular lives in a special world, where it's technically using the dark theme values -- so i think it would be fine for it to use --dark-theme-text-color directly, since that's what it actually needs. It can't use the default --primary-text-color because it's using the exact opposite theme of whatever the other elements use (also, if the other elements were switched to use the dark theme, paper-fab would need to independently switch to --dark-theme-text-color
-------------------------------------------------------------------------

Ouch. I see the issue.

-----------------------------------------------------------------------------
I think the issues are orthogonal, and I don't really see why elements can't use the theme colours directly in their styles, if that's the colours you need. It will make them harder to style all at once, but this isn't worse than today, when you would have to hardcode the paper-fab colour to white anyway, since it's not in line with the rest of the paper elements
------------------------------------------------------------------------------------

OK. I am not 1000% convinced that it's sane for elements and applications to use both `--light-theme-*`/`--dark-theme=*` _and_ the theming values of the paper widgets. Points:

*  `--primary-text-color` and `--light-theme-text-color` (as well as any other inter-dependent pair in `default-theme.html`) must match if they can be used interchangeably by different Polymer elements or by different parts of an application;

* It should be documented that the "correct" way of theming is by changing the values in `--light-theme-*`/`--dark-theme=*` since they can potentially be used and must be in sync

* It's a bit strange that `paper-fab` is the only one widget that ever uses `--light-theme-*`/`--dark-theme=*`

I don't mean to be difficult. I am just a consistency and simplicity freak -- apologies if I am being unnecessarily painful.
