### ISSUE TITLE
default-theme:  Why hex instead of rgba?

### ISSUE THREAD

**Issue by robrez** [PolymerElements/paper-styles#60]
The hex values match the MD spec when used on a 100% white background.

If some other "light" background is used, then the values specified on the MD spec will begin to deviate from the hex values. For example..

```
  .white-bg {
    background-color: #fff;
    color: rgba(0,0,0,.87);  /* matches #212121 */
  }
  .grey-bg {
    background-color: #eee;
    color: rgba(0,0,0,.87);  /* not #212121..  is #1f1f1f */
  }
```

_I did notice minor discrepancies on the following two props:_
- `divider-color: #e0e0e0;`. black 12% computes to `#e1e1e1` for me
- `disabled-text-color: #bdbdbd;`. black 38% computes to `#9e9e9e` for me

Not to split hairs! -- I'm mostly curious if there were a reason, performance or otherwise) usage of hex is preferable to rgba.

**Comment by notwaldorf** [comment]
I think we used hex because that's how they were listen in the Material Design spec (https://www.google.com/design/spec/style/color.html), and we just copied them from there. Most of the colours are opaque, so that wasn't a prolem.

You are probably right about the divider and disabled text color discrepancies, and we would totally accept a PR to fix that :)

**Comment by robrez** [comment]
Thanks for the feedback. I should have clarified that the text colors were the main bits I was curious about (primary-text-color, secondary-text-color). The spec mention transparency in a couple of spots regarding text color

>Transparent black or white text behaves more flexibly than grey text because it remains legible and vibrant against background color changes.

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3Z21kckdVNjFiN2c/style_color_uiapplication_alpha1.png

https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3dGx2T1FqM0xXbTA/style_typography_styles_contrast.png

**Comment by ronnyroeller** [comment]
The spec actually advises explicitly transparency over grey text:
"Transparent black or white text behaves more flexibly than grey text because it remains legible and vibrant against background color changes." (https://www.google.com/design/spec/style/color.html#color-ui-color-application)

**Comment by ronnyroeller** [comment]
+1

**Comment by notwaldorf** [comment]
We've recently found out that rgba colours are actually more expensive when painting (https://github.com/PolymerElements/paper-styles/pull/74#issuecomment-161119927), because you have to apply the opacity after calculating the background. I think we're going to stay away from doing this change now, since the gains aren't worth the paint cost :(

**Comment by robrez** [comment]
That comment thread has some great info... Thanks!
