### ISSUE TITLE
Remove old branches

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-styles#70]
I think that we can remove the old [branches](https://github.com/PolymerElements/paper-styles/branches):

- `fix-mobile-size` (already merged)
- `font-common-base` (already merged)
- `iron-flex-layout` (already closed)
- `shadow-none` (already merged)
- `x-typography` (already merged)

**Comment by notwaldorf** [comment]
@abdonrd As I'm going through all the repos that you opened this issue on, I would like to make a general comment: this issue isn't really useful for us, and it's really tedious to address. There's no cost with having branches in a repo, nor do they hurt anything by existing, so this isn't actually a real issue. Unless you provide us with an automatic script to do this, we now manually have to go through 30+ repos, delete these branches, and close all of these issues, to solve no apparent problem.

We try very hard to stay on top of new issues and triage them as they come along, and triaging is actually a time consuming operation. In the future, if you intend to open these kind of automatic issues, please open a generic issue on the product line (in this case, `paper-elements`), rather than spamming all the repos with issues.

**Comment by abdonrd** [comment]
@notwaldorf I understand, sorry for the inconvenience. :pensive:

I suggested to remove old branches because when I opening SourceTree all these branches generate "noise". But I understand that this has no more relevance.
